version: "3.8"
services:
    # The main service : RDFMiner
    rdfminer:
        restart: always
        image: rdfminer:1.4
        build:
            context: ./RDFMiner/.
        depends_on:
            - virtuoso
        command: launch
        volumes:
            - /home/xxx/projects/RDFMining/IO:/rdfminer/io           # To use it in your own machine, you need to put your own absolute path
        networks:
            rdfmining_network:
                ipv4_address: 172.19.0.3
    # OpenLink Virtuoso v7.2.5
    # Used by RDFMiner to load and query a training dataset
    virtuoso:
        restart: always
        image: virtuoso:1.0
        build:
            context: ./Virtuoso/.
        ports:
            - "9000:9000"
        volumes:
            - /home/xxx/projects/RDFMining/Virtuoso/data:/data       # To use it in your own machine, you need to put your own absolute path
        networks:
            rdfmining_network:
                ipv4_address: 172.19.0.2
    # Corese 4.3.0
    corese:
        restart: always
        image: corese:4.3.0
        build: 
            context: ./Corese/.
        ports:
            - "9100:9100"
        volumes:
            - /home/xxx/projects/RDFMining/Corese/log:/usr/local/corese/log      # To use it in your own machine, you need to put your own absolute path
            - /home/xxx/projects/RDFMining/Corese/data:/usr/local/corese/data    # To use it in your own machine, you need to put your own absolute path
        networks:
            rdfmining_network:
                ipv4_address: 172.19.0.4
networks:
    rdfmining_network:
        ipam:
            config:
                - subnet: 172.19.0.0/24
