version: "3.8"
services:
    # The main service : RDFMiner
    # developed by Andrea G. B. Tettamanzi, Thu Huong Nguyen and Rémi Felin
    rdfminer:
        restart: always
        image: rdfminer:1.3
        build:
            context: ./RDFMiner/.
        depends_on:
            - virtuoso
        command: launch
        volumes:
            - /home/remi/Bureau/dev/RDFMining/IO:/rdfminer/io # To use it in your own machine, you need to put your own absolute path
        networks:
            rdfminer_network:
                ipv4_address: 172.19.0.3
    virtuoso:
        restart: always
        image: virtuoso:1.0
        build:
            context: ./Virtuoso/.
        ports:
            - "9000:9000"
        volumes:
            - /home/remi/Bureau/dev/RDFMining/Virtuoso/data:/data # To use it in your own machine, you need to put your own absolute path
        networks:
            rdfminer_network:
                ipv4_address: 172.19.0.2
networks:
    rdfminer_network:
        ipam:
            config:
                - subnet: 172.19.0.0/24
