/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rdfminer_entity_Entity */

#ifndef _Included_rdfminer_entity_Entity
#define _Included_rdfminer_entity_Entity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_i3s_app_rdfminer_entity_Entity
 * Method:    getProcessCPUTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_i3s_app_rdfminer_entity_Entity_getProcessCPUTime
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
