/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rdfminer_axiom_Axiom */

#ifndef _Included_rdfminer_axiom_Axiom
#define _Included_rdfminer_axiom_Axiom
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_i3s_app_rdfminer_axiom_Axiom
 * Method:    getProcessCPUTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_i3s_app_rdfminer_axiom_Axiom_getProcessCPUTime
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
